header done
DVShanina/skipscholarship.github.io pull request #2
Opened 2022-10-12 06:35 UTC by DVShanina

2022-10-12 07:29 UTC, Ivanescope requested changes

2022-10-12 07:29 UTC, Ivanescope commented on src/App.jsx
> +  return <RoutesPage/>  }
лучше просто Routes, без Page, все таки это не страница

2022-10-12 07:29 UTC, Ivanescope commented on src/components/Header/Header.jsx
> +        <header className="header-block">
слово block можно вообще убрать, чисто header будет класс называть, так более понятно, блок - особо ничего не добавляет в названии, тэг header и так блок по умолчанию

2022-10-12 07:29 UTC, Ivanescope commented on src/components/Header/Header.jsx
> +            <div className="header-block_link">
через одно нижнее подчеркивание указывается модификатор, то есть[ состояние или поведение блока либо элемента](https://ru.bem.info/methodology/quick-start/#%D0%BC%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80)

2022-10-12 07:29 UTC, Ivanescope commented on src/components/Header/Header.jsx
> +            <div className="header-block_link">
в данном случае link, form, button это будут элементы, так как они "[Название элемента](https://ru.bem.info/methodology/naming-convention/#%D0%98%D0%BC%D1%8F-%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D0%B0) характеризует смысл («что это?» — «пункт»: item, «текст»: text), а не состояние («какой, как выглядит?» — «красный»: red, «большой»: big)."

2022-10-12 07:29 UTC, Ivanescope commented on src/components/Header/Header.jsx
> +            <div className="header-block_link">
либо же они могут быть блоком, [когда создавать блок когда элемент](https://ru.bem.info/methodology/quick-start/#%D0%BA%D0%BE%D0%B3%D0%B4%D0%B0-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%B2%D0%B0%D1%82%D1%8C-%D0%B1%D0%BB%D0%BE%D0%BA-%D0%BA%D0%BE%D0%B3%D0%B4%D0%B0--%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82)

2022-10-12 07:29 UTC, Ivanescope commented on src/components/Header/Header.scss
> +    .header-block_link {
в scss можно еще для вложенных элементов писать более короткие записи, например - 

.header-block {
    position: absolute;

    &__link {
       font-family: 'Roboto Slab';
    }
}

2022-10-12 07:29 UTC, Ivanescope commented on src/components/Header/Header.scss
> +            background: #0073E6;
значения, которые могут несколько раз повторятся, например цвета, выносятся обычно в отдельный scss файл variables и потом импортируются средствами scss (в scss тоже есть import, чуть по другому пишется только)

либо можешь через обычные css  переменные, как тебе будет удобнее

2022-10-12 07:29 UTC, Ivanescope commented on src/components/Header/Header.scss
> +            background: #0073E6;
в общем то, что повторяется 2 или больше раз  можно выносить в переменную)

2022-10-12 07:29 UTC, Ivanescope commented on src/index.jsx
> +import "./components/Header/Header.scss"
Эту строчку лучше написать в `src/components/Header/Header.jsx`, т.е. стили, окторые относятся только Header импортируешь в компоненте Header, то что относится к Button, в компоненте Button

2022-10-12 07:29 UTC, Ivanescope commented on src/pages/PlaceDetail.jsx
> +    <React.StrictMode>
<React.StrictMode>  лучше вынести в App.jsx  и обернуть Routes, тогда запись <React.StrictMode>  можно будет всего один раз написать

2022-10-12 07:29 UTC, Ivanescope commented on src/components/Header/Header.jsx
> +                <Link to ="/Edit"> Добавить место </Link>
Тут можешь пока без Link, потому что на добавление будет отдельная модалка, она без роута будет

2022-10-12 07:29 UTC, Ivanescope commented on src/components/Header/Header.scss
> +    font-family: 'Roboto';
он точно тут нужен, видел его в общих стилях для body, по идее в таком случае по всему проекту будет Roboto

2022-10-12 07:29 UTC, Ivanescope commented on src/scss/base.scss
> +  margin-top: 100px;
обычно в общих стилях не пишут margin, padding, position, потому что если в другом месте где-то захочется использовать h2, то везде нужно будет обнулять этот стиль, в общих обычно пишут шрифты, могут размер шрифта, в общем какие-то общие стили

2022-10-12 11:34 UTC, DVShanina commented on src/App.jsx
> +  return <RoutesPage/>  }
Я так пыталась сразу сделать, но Routes уже импортируется из react-router-dom, у меня код ругается

2022-10-12 12:42 UTC, DVShanina commented on src/scss/base.scss
> +  margin-top: 100px;
Это я написала, чтобы h2 видно было, а то он тонул под header)

2022-10-12 15:51 UTC, OlesiaTenkova commented on src/components/Header/Header.jsx
> +                <p className="header__form__lable">₽</p>
лучше использовать span или просто div, тег p используют обычно как параграф в тексте

2022-10-12 15:51 UTC, OlesiaTenkova commented on src/components/Header/Header.scss
> +$color-button: #0073E6;
лучше назвать например color-blue или какой там цвет color-light-blue и вынести эти переменные в отдельный файлик variables.scss, потом использовать его в других компонентах тоже

2022-10-12 15:51 UTC, OlesiaTenkova commented on src/components/Header/Header.scss
> +$second-font:'Roboto Slab';
вроде шрит не подключен, ну по ссылке не тот отображается, посмотри на google fonts

2022-10-12 15:51 UTC, OlesiaTenkova commented on src/scss/base.scss
> +  padding: 0 10% 0 10%;
точно лишнее) из-за этого тебе пришлось у header делать position: absolute

2022-10-12 15:51 UTC, OlesiaTenkova commented on src/components/Header/Header.scss
> +    position: absolute;
не нужно position: absolute;
Чтобы по бокам был отступ можно создать еще один вложенный блок например header__content и задать ему максимальную ширина 1240 и расположить его по середине, а уже внутри него положить логотип, форму и кнопку

2022-10-12 15:51 UTC, OlesiaTenkova commented on src/components/Header/Header.scss
> +        width: 28%;
лучше не писать такую ширину) и вообще как ты ее высчитала))
попробуй логотип расположить слева,
а кнопку справа(с левым отступом) и форму тоже слева чтобы она шла за кнопкой (флексами все вроде можно сделать)

2022-10-12 15:51 UTC, OlesiaTenkova commented on src/components/Header/Header.scss
> +        &__input {
когда инпут в фокусе - не должно появляться рамки

2022-10-12 15:51 UTC, OlesiaTenkova commented on src/components/Header/Header.scss
> +    &__button {
кнопкам часто добавляют cursor: pointer чтобы она выглядела кликабельной

2022-10-12 15:55 UTC, Ivanescope commented on src/App.jsx
> +  return <RoutesPage/>  }
то есть когда пишешь `import Routes from "./routes";` что-то ругается?

2022-10-12 16:04 UTC, DVShanina commented on src/App.jsx
> +  return <RoutesPage/>  }
когда функцию называю Routes, пишет, что уже декларировано

2022-10-13 08:11 UTC, Ivanescope commented on src/components/Header/Header.jsx
> +                <p className="header__form__lable">₽</p>
и еще по бэму не может быть несколько классов подряд)
тут скорее всего label это элемент, он через одно подчеркивание

2022-10-13 08:11 UTC, Ivanescope commented on src/components/Header/Header.jsx
> +                <label className="header__form__lable" for="header__form__input" >Размер стипендии </label>
label и input элементы

2022-10-13 08:11 UTC, Ivanescope commented on src/pages/NotFound.jsx
> +  <div>
Еще если не нужно никаких обработчиков вешать на элемент или стилей, то лучше будет использовать [Fragment](https://ru.reactjs.org/docs/fragments.html)

там есть короткая запить <>...</>😅

2022-10-13 08:11 UTC, Ivanescope commented on src/pages/PlaceDetail.jsx
> +      <React.Fragment>
оо, а здесь уже использовала👍

2022-10-13 08:11 UTC, Ivanescope commented on src/scss/base.scss
> +  margin-top: 100px;
это, наверное, из-за absolute, лучше absolute  не юзать где можно, давай попробуем весь абсолют выпилить)

2022-10-13 08:11 UTC, Ivanescope commented on src/scss/base.scss
> +.NotFound {
.not-found {}

2022-10-13 08:11 UTC, Ivanescope commented on src/scss/base.scss
> +.NotFound {
CamelCase в js, тут через дефис и подчеркивания)

2022-10-13 08:11 UTC, Ivanescope commented on src/components/Header/Header.scss
> +    width: 80vw;
когда уберешь абсолют и это свойство не понадобиться

2022-10-13 08:11 UTC, Ivanescope commented on src/components/Header/Header.jsx
> +                <label className="header__form__lable" for="header__form__input" >Размер стипендии </label>
@DVShanina вот тут еще не поправила)
там еще не lable, а label)

2022-10-13 08:11 UTC, Ivanescope commented on src/scss/base.scss
> +.NotFound {
@DVShanina

2022-10-13 13:11 UTC, merged

2022-10-18 18:30 UTC, Ivanescope commented on src/components/Header/Header.jsx
> +            <div className="header__link">
тут лучше название logo подойдет `header__logo`