slider, rating, select
DVShanina/skipscholarship.github.io pull request #4
Opened 2022-10-24 08:07 UTC by DVShanina

2022-10-25 08:54 UTC, Ivanescope requested changes

2022-10-25 08:54 UTC, Ivanescope commented on src/components/Header/Header.scss
> +    padding: 0 5% 0 5%;
тут можно `padding: 0 5%; `

2022-10-25 08:54 UTC, Ivanescope commented on package.json
> +    "react-awesome-stars-rating": "^0.13.0",
Зачем вот эта либа нужна? она вроде нигде не используется?

2022-10-25 08:54 UTC, Ivanescope commented on src/components/Slider/Slider.jsx
> +Сколько: {ReactSlider.ariaValuetext} {/* не понимаю, как это сделать, чтобы я не пробовала, не работает  */}
тут тебе надо сделать так же как в RatingStars, завести локальный стейт, в него записывать значения, которые ты можешь получить в onChange и потом выводить этот стейт здесь

2022-10-25 08:54 UTC, Ivanescope commented on src/components/Slider/Slider.scss
> +    //background: yellow;
этот коммент наверное не нужен

2022-10-25 08:54 UTC, Ivanescope commented on src/scss/base.scss
> +  // padding: 5px 0 0 5%;
Эти комментарии если не нужны, то строчки удалить нужно

2022-10-25 08:54 UTC, Ivanescope commented on src/scss/base.scss
> +  // padding: 5px 0 0 5%;
либо оставить комментарий зачем нужны они, если они потом понадобятся

2022-10-25 08:54 UTC, Ivanescope commented on package.json
> +    "react-star-ratings": "^2.3.0",
и вот это не понял зачем?

2022-10-25 08:54 UTC, Ivanescope commented on package.json
> +    "react-star-ratings": "^2.3.0",
может ты пробовала несколько библиотек, если они не используются лучше их удалить, так как они создают дополнительный вес проекту

2022-10-25 08:54 UTC, Ivanescope commented on src/components/Rating/Rating.jsx
> +    // Optinal callback functions
комменты можешь не оставлять из библиотек, если они тебе самой не нужны

2022-10-25 08:54 UTC, Ivanescope commented on src/components/Rating/Rating.jsx
> +    const onPointerMove = (value, index) => console.log(value, index)
Эти три обработчика они нам не пригодятся скорее всего, хватит одного handleChangeRating

2022-10-25 08:54 UTC, Ivanescope commented on src/components/Rating/Rating.jsx
> +    const handleRating = (rate) => {
чуть более говорящее название `handleChangeRating`

2022-10-25 08:54 UTC, Ivanescope commented on src/components/Rating/Rating.jsx
> +          /* Available Props */
не нуден этот коммент

2022-10-25 08:54 UTC, Ivanescope commented on src/components/Slider/Slider.jsx
> + thumbClassName="example-thumb"
лучше слова типа example, test не использовать в названиях классов/компонентов/переменных, если только они не отображают суть сущности

2022-10-25 08:54 UTC, Ivanescope commented on src/components/Slider/Slider.scss
> +  }
.example-track {
    position: relative;
    background: $color-blue;
    top: 15px;
    height: 4px;
 
    .example-track-0 {
      background: $color-light-gray;
    }
    .example-track-2 {
      background: $color-light-gray;
    }
}

2022-10-25 08:54 UTC, Ivanescope commented on src/components/Rating/Rating.jsx
> +      <span className="filteres__lable">Как:</span>
тут опечатка, lable -> label

2022-10-25 08:54 UTC, Ivanescope commented on src/components/Rating/Rating.jsx
> +      <span className="filteres__lable">Как:</span>
вообще не нашел этот класс в scss

2022-10-25 08:54 UTC, Ivanescope commented on src/components/Rating/Rating.jsx
> +      <div className="filteres__renge">
`renge` -> `range`

2022-10-25 08:54 UTC, Ivanescope commented on src/components/Slider/Slider.jsx
> +<span className="filteres__lable">
нет класса

2022-10-25 08:54 UTC, Ivanescope commented on src/components/Slider/Slider.jsx
> +<div className="filteres__slider">
тоже нет класса

2022-10-25 08:54 UTC, Ivanescope commented on src/pages/PlaceList.jsx
> +              <div className="filteres__group filteres__group_grow1">
filteres__group_grow1 - вроде без этого класса все так же работает

2022-10-25 08:54 UTC, Ivanescope commented on src/pages/PlaceList.jsx
> +              <div className="filteres__group filteres__group_width">
filteres__group_width название не говорящее, тип width какое угодно может быть, над что-то поинформативнее придумать

2022-10-25 12:00 UTC, DVShanina commented on package.json
> +    "react-awesome-stars-rating": "^0.13.0",
Сначала ее пробовала, потом другую)

2022-10-26 11:39 UTC, Ivanescope commented on src/components/Rating/Rating.jsx
> +          onClick={handleChangeRating}
можно просто onClick={setRating}

2022-10-26 11:39 UTC, Ivanescope commented on src/components/Slider/Slider.jsx
> + onChange={handleChangeValue}
здесь тоже onChange={setValue}, но лучше найти название передающее смысл, что происходит
onChange={setSliderPosition} может быть)

2022-10-26 11:39 UTC, Ivanescope commented on src/components/Slider/Slider.jsx
> +
кажется лишние пробелы какие -то)

2022-10-26 11:39 UTC, Ivanescope commented on src/pages/PlaceList.jsx
> +              <div className="filteres__group filteres__group_260px">
наверное не правильно выразился в прошлом коммите, имел ввиду, что вообще не оч хорошая практика придумывать классы под один стиль

можно назвать классс `filters__rating`

2022-10-26 11:39 UTC, Ivanescope commented on src/pages/PlaceList.jsx
> +              <div className="filteres__group filteres__group_260px">
filters__place

2022-10-26 11:39 UTC, Ivanescope commented on src/pages/PlaceList.jsx
> +        <section className="filteres">
`filteres` -> `filters`

2022-10-26 11:39 UTC, Ivanescope commented on src/scss/PlaceList.scss
> +    padding: 0 5% 0 5%;
padding: 0 5%;

2022-10-26 11:41 UTC, Ivanescope commented on src/scss/PlaceList.scss
> +    width: 100vw;
width: 100%

2022-10-26 19:31 UTC, Ivanescope commented on src/pages/PlaceList.jsx
> +                  <span className="filters__lable">Где:</span>
`lable` -> `label`

Уже была такая ошибка)

2022-10-26 19:31 UTC, Ivanescope commented on src/scss/PlaceList.scss
> -        padding: 0 10px 0 10px;
Like

2022-10-26 19:32 UTC, merged